"""empty message

Revision ID: 4238c523a018
Revises: ca34f30eb86e
Create Date: 2020-07-16 18:38:57.738157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4238c523a018'
down_revision = 'ca34f30eb86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint('vacancies_speciality_code_fkey', 'vacancies', type_='foreignkey')
    op.drop_constraint('vacancies_company_name_fkey', 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'companies', ['company_name'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'specialities', ['speciality_code'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key('vacancies_company_name_fkey', 'vacancies', 'companies', ['company_name'], ['name'])
    op.create_foreign_key('vacancies_speciality_code_fkey', 'vacancies', 'specialities', ['speciality_code'], ['code'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
