"""empty message

Revision ID: 6fffe2f5faae
Revises: 
Create Date: 2020-07-26 17:54:54.419322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fffe2f5faae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('written_username', sa.String(), nullable=False),
    sa.Column('written_phone', sa.String(), nullable=False),
    sa.Column('written_cover_letter', sa.Text(), nullable=False),
    sa.Column('vacancy_app', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_app'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('employee_count', sa.String(), nullable=True),
    sa.Column('owner_companies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_companies'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('user_app', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_app'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary_min', sa.String(), nullable=True),
    sa.Column('salary_max', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('speciality_code', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['speciality_code'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('users')
    op.drop_table('specialities')
    op.drop_table('companies')
    op.drop_table('applications')
    # ### end Alembic commands ###
