"""empty message

Revision ID: ca34f30eb86e
Revises: 
Create Date: 2020-07-15 21:31:52.990717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca34f30eb86e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('vacancy_app', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'vacancies', ['vacancy_app'], ['id'])
    op.add_column('companies', sa.Column('owner_companies', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['owner_companies'], ['id'])
    op.add_column('users', sa.Column('user_app', sa.Integer(), nullable=True))
    op.drop_constraint('users_user_companies_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'applications', ['user_app'], ['id'])
    op.drop_column('users', 'user_companies')
    op.drop_constraint('vacancies_vacancy_apps_fkey', 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'vacancy_apps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('vacancy_apps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vacancies_vacancy_apps_fkey', 'vacancies', 'applications', ['vacancy_apps'], ['id'])
    op.add_column('users', sa.Column('user_companies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_user_companies_fkey', 'users', 'companies', ['user_companies'], ['id'])
    op.drop_column('users', 'user_app')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'owner_companies')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'vacancy_app')
    # ### end Alembic commands ###
